export const obj = [
    {
        id: 1,
        title: "Лаборатория мультимедиа",
        func: "Современные технологии добычи нефти",
        initiator: "Рыжкова Елена Александровна",
        position: "Аналитик сменная должность",
        date: "12.04.2017",
        program: "Организация и управление инженерными изысканиями Организация и управление инженерными изысканиями",
        cost: 200,
        status: "Согласование линейным руководителем"
    },
    {
      id: 1,
      title: "Лаборатория мультимедиа",
      func: "Современные технологии добычи нефти",
      initiator: "Рыжкова Елена Александровна",
      position: "Аналитик сменная должность",
      date: "12.04.2017",
      program: "Организация и управление инженерными изысканиями Организация и управление инженерными изысканиями",
      cost: 200,
      status: "Согласование линейным руководителем"
    },
    {
      id: 1,
      title: "Лаборатория",
      func: "Современные технологии добычи нефти",
      initiator: "Рыжкова Елена Александровна",
      position: "Аналитик",
      date: "12.04.2017",
      program: "Организация и управление инженерными изысканиями",
      cost: 700,
      status: "Согласование"
    },
    {
        id: 1,
        title: "Лаборатория мультимедиа",
        func: "Современные технологии добычи нефти",
        initiator: "Рыжкова Елена Александровна",
        position: "Аналитик сменная должность",
        date: "12.04.2017",
        program: "Организация и управление инженерными изысканиями Организация и управление инженерными изысканиями",
        cost: 200,
        status: "Согласование линейным руководителем"
    },
    {
      id: 1,
      title: "Лаборатория",
      func: "Современные технологии добычи нефти",
      initiator: "Рыжкова Елена Александровна",
      position: "Аналитик",
      date: "12.04.2017",
      program: "Организация и управление инженерными изысканиями",
      cost: 700,
      status: "Согласование"
    },
    {
      id: 1,
      title: "Лаборатория",
      func: "Современные технологии добычи нефти",
      initiator: "Рыжкова Елена Александровна",
      position: "Аналитик",
      date: "12.04.2017",
      program: "Организация и управление инженерными изысканиями",
      cost: 700,
      status: "Согласование"
    },
    {
        id: 1,
        title: "Лаборатория мультимедиа",
        func: "Современные технологии добычи нефти",
        initiator: "Рыжкова Елена Александровна",
        position: "Аналитик сменная должность",
        date: "12.04.2017",
        program: "Организация и управление инженерными изысканиями Организация и управление инженерными изысканиями",
        cost: 200,
        status: "Согласование линейным руководителем"
    },
    {
        id: 1,
        title: "Лаборатория мультимедиа",
        func: "Современные технологии добычи нефти",
        initiator: "Рыжкова Елена Александровна",
        position: "Аналитик сменная должность",
        date: "12.04.2017",
        program: "Организация и управление инженерными изысканиями Организация и управление инженерными изысканиями",
        cost: 200,
        status: "Согласование линейным руководителем"
    },
    {
        id: 1,
        title: "Лаборатория мультимедиа",
        func: "Современные технологии добычи нефти",
        initiator: "Рыжкова Елена Александровна",
        position: "Аналитик сменная должность",
        date: "12.04.2017",
        program: "Организация и управление инженерными изысканиями Организация и управление инженерными изысканиями",
        cost: 200,
        status: "Согласование линейным руководителем"
    },
    {
      id: 1,
      title: "Graham Terra",
      func: "Do veniam tempor sunt sit tempor elit.",
      initiator: "Carey Atkins Kim",
      position: "Wilkins Rodgers",
      date: "Mon Oct 23 1989 09:44:54 GMT+0300 (GMT+03:00)",
      program: "Jannie Marva Lyons Nicholson",
      cost: 926,
      status: "Alison Phelps"
    },
    {
      id: 1,
      title: "Graham Terra",
      func: "Do veniam tempor sunt sit tempor elit.",
      initiator: "Carey Atkins Kim",
      position: "Wilkins Rodgers",
      date: "Mon Oct 23 1989 09:44:54 GMT+0300 (GMT+03:00)",
      program: "Jannie Marva Lyons Nicholson",
      cost: 926,
      status: "Alison Phelps"
    },
    {
        id: 1,
        title: "Лаборатория мультимедиа",
        func: "Современные технологии добычи нефти",
        initiator: "Рыжкова Елена Александровна",
        position: "Аналитик сменная должность",
        date: "12.04.2017",
        program: "Организация и управление инженерными изысканиями Организация и управление инженерными изысканиями",
        cost: 200,
        status: "Согласование линейным руководителем"
    },
    {
      id: 1,
      title: "Graham Terra",
      func: "Do veniam tempor sunt sit tempor elit.",
      initiator: "Carey Atkins Kim",
      position: "Wilkins Rodgers",
      date: "Mon Oct 23 1989 09:44:54 GMT+0300 (GMT+03:00)",
      program: "Jannie Marva Lyons Nicholson",
      cost: 926,
      status: "Alison Phelps"
    },
    {
      id: 1,
      title: "Лаборатория",
      func: "Современные технологии добычи нефти",
      initiator: "Рыжкова Елена Александровна",
      position: "Аналитик",
      date: "12.04.2017",
      program: "Организация и управление инженерными изысканиями",
      cost: 700,
      status: "Согласование"
    },
    {
      id: 1,
      title: "Лаборатория",
      func: "Современные технологии добычи нефти",
      initiator: "Рыжкова Елена Александровна",
      position: "Аналитик",
      date: "12.04.2017",
      program: "Организация и управление инженерными изысканиями",
      cost: 700,
      status: "Согласование"
    },
    {
        id: 1,
        title: "Лаборатория мультимедиа",
        func: "Современные технологии добычи нефти",
        initiator: "Рыжкова Елена Александровна",
        position: "Аналитик сменная должность",
        date: "12.04.2017",
        program: "Организация и управление инженерными изысканиями Организация и управление инженерными изысканиями",
        cost: 200,
        status: "Согласование линейным руководителем"
    },
    {
      id: 1,
      title: "Graham Terra",
      func: "Do veniam tempor sunt sit tempor elit.",
      initiator: "Carey Atkins Kim",
      position: "Wilkins Rodgers",
      date: "Mon Oct 23 1989 09:44:54 GMT+0300 (GMT+03:00)",
      program: "Jannie Marva Lyons Nicholson",
      cost: 926,
      status: "Alison Phelps"
    },
    {
      id: 1,
      title: "Graham Terra",
      func: "Do veniam tempor sunt sit tempor elit.",
      initiator: "Carey Atkins Kim",
      position: "Wilkins Rodgers",
      date: "Mon Oct 23 1989 09:44:54 GMT+0300 (GMT+03:00)",
      program: "Jannie Marva Lyons Nicholson",
      cost: 926,
      status: "Alison Phelps"
    },
    {
      id: 1,
      title: "Graham Terra",
      func: "Do veniam tempor sunt sit tempor elit.",
      initiator: "Carey Atkins Kim",
      position: "Wilkins Rodgers",
      date: "Mon Oct 23 1989 09:44:54 GMT+0300 (GMT+03:00)",
      program: "Jannie Marva Lyons Nicholson",
      cost: 926,
      status: "Alison Phelps"
    },
    {
        id: 1,
        title: "Лаборатория мультимедиа",
        func: "Современные технологии добычи нефти",
        initiator: "Рыжкова Елена Александровна",
        position: "Аналитик сменная должность",
        date: "12.04.2017",
        program: "Организация и управление инженерными изысканиями Организация и управление инженерными изысканиями",
        cost: 200,
        status: "Согласование линейным руководителем"
    },
    {
      id: 1,
      title: "Graham Terra",
      func: "Do veniam tempor sunt sit tempor elit.",
      initiator: "Carey Atkins Kim",
      position: "Wilkins Rodgers",
      date: "Mon Oct 23 1989 09:44:54 GMT+0300 (GMT+03:00)",
      program: "Jannie Marva Lyons Nicholson",
      cost: 926,
      status: "Alison Phelps"
    },
    {
      id: 1,
      title: "Graham Terra",
      func: "Do veniam tempor sunt sit tempor elit.",
      initiator: "Carey Atkins Kim",
      position: "Wilkins Rodgers",
      date: "Mon Oct 23 1989 09:44:54 GMT+0300 (GMT+03:00)",
      program: "Jannie Marva Lyons Nicholson",
      cost: 926,
      status: "Alison Phelps"
    },
    {
        id: 1,
        title: "Graham Terra",
        func: "Do veniam tempor sunt sit tempor elit.",
        initiator: "Carey Atkins Kim",
        position: "Wilkins Rodgers",
        date: "Mon Oct 23 1989 09:44:54 GMT+0300 (GMT+03:00)",
        program: "Jannie Marva Lyons Nicholson",
        cost: 926,
        status: "Alison Phelps"
      },
      {
        id: 1,
        title: "Graham Terra",
        func: "Do veniam tempor sunt sit tempor elit.",
        initiator: "Carey Atkins Kim",
        position: "Wilkins Rodgers",
        date: "Mon Oct 23 1989 09:44:54 GMT+0300 (GMT+03:00)",
        program: "Jannie Marva Lyons Nicholson",
        cost: 926,
        status: "Alison Phelps"
      },
      {
        id: 1,
        title: "Graham Terra",
        func: "Do veniam tempor sunt sit tempor elit.",
        initiator: "Carey Atkins Kim",
        position: "Wilkins Rodgers",
        date: "Mon Oct 23 1989 09:44:54 GMT+0300 (GMT+03:00)",
        program: "Jannie Marva Lyons Nicholson",
        cost: 926,
        status: "Alison Phelps"
      },
      {
        id: 1,
        title: "Graham Terra",
        func: "Do veniam tempor sunt sit tempor elit.",
        initiator: "Carey Atkins Kim",
        position: "Wilkins Rodgers",
        date: "Mon Oct 23 1989 09:44:54 GMT+0300 (GMT+03:00)",
        program: "Jannie Marva Lyons Nicholson",
        cost: 926,
        status: "Alison Phelps"
      },
      {
        id: 1,
        title: "Graham Terra",
        func: "Do veniam tempor sunt sit tempor elit.",
        initiator: "Carey Atkins Kim",
        position: "Wilkins Rodgers",
        date: "Mon Oct 23 1989 09:44:54 GMT+0300 (GMT+03:00)",
        program: "Jannie Marva Lyons Nicholson",
        cost: 926,
        status: "Alison Phelps"
      },
      {
        id: 1,
        title: "Graham Terra",
        func: "Do veniam tempor sunt sit tempor elit.",
        initiator: "Carey Atkins Kim",
        position: "Wilkins Rodgers",
        date: "Mon Oct 23 1989 09:44:54 GMT+0300 (GMT+03:00)",
        program: "Jannie Marva Lyons Nicholson",
        cost: 926,
        status: "Alison Phelps"
      },
      {
        id: 1,
        title: "Graham Terra",
        func: "Do veniam tempor sunt sit tempor elit.",
        initiator: "Carey Atkins Kim",
        position: "Wilkins Rodgers",
        date: "Mon Oct 23 1989 09:44:54 GMT+0300 (GMT+03:00)",
        program: "Jannie Marva Lyons Nicholson",
        cost: 926,
        status: "Alison Phelps"
      },
      {
        id: 1,
        title: "Graham Terra",
        func: "Do veniam tempor sunt sit tempor elit.",
        initiator: "Carey Atkins Kim",
        position: "Wilkins Rodgers",
        date: "Mon Oct 23 1989 09:44:54 GMT+0300 (GMT+03:00)",
        program: "Jannie Marva Lyons Nicholson",
        cost: 926,
        status: "Alison Phelps"
      },
      {
        id: 1,
        title: "Graham Terra",
        func: "Do veniam tempor sunt sit tempor elit.",
        initiator: "Carey Atkins Kim",
        position: "Wilkins Rodgers",
        date: "Mon Oct 23 1989 09:44:54 GMT+0300 (GMT+03:00)",
        program: "Jannie Marva Lyons Nicholson",
        cost: 926,
        status: "Alison Phelps"
      },
      {
        id: 1,
        title: "Graham Terra",
        func: "Do veniam tempor sunt sit tempor elit.",
        initiator: "Carey Atkins Kim",
        position: "Wilkins Rodgers",
        date: "Mon Oct 23 1989 09:44:54 GMT+0300 (GMT+03:00)",
        program: "Jannie Marva Lyons Nicholson",
        cost: 926,
        status: "Alison Phelps"
      },
      {
        id: 1,
        title: "Graham Terra",
        func: "Do veniam tempor sunt sit tempor elit.",
        initiator: "Carey Atkins Kim",
        position: "Wilkins Rodgers",
        date: "Mon Oct 23 1989 09:44:54 GMT+0300 (GMT+03:00)",
        program: "Jannie Marva Lyons Nicholson",
        cost: 926,
        status: "Alison Phelps"
      },
  ]